type Query {
    hello: String!
    hello1: String!
    hello2: String!
}

type Mutation {
    createUser(name: String!): String!
    createUser1(name: String!): String!
    createUser2(name: String!): User!
}

"""
User type serves as a representation for storing user details, such as name or other relevant data fields for demonstration purposes.
"""
type User {
    """
    Name of the user.
    """
    name: String!
}
